(ns exercise)
(prn (assoc {:a 1} :b 2))
(prn (mapv inc [1 2 3]))
(prn (reduce + (range 10)))
(prn (str "x" 1 :kw 'sym [1 2] {:a 1} #{3}))
(prn (into {} (map (fn [x] [x (* x x)]) (range 3))))
(def a (atom {:n 0}))
(swap! a update :n inc)
(prn @a)
(defprotocol IThing (thing [_]))
(deftype T [x] IThing (thing [_] x))
(prn (thing (->T 42)))
(defmulti area :shape)
(defmethod area :square [{:keys [side]}] (* side side))
(prn (area {:shape :square :side 3}))
(prn (sort (shuffle [3 1 2])))
(prn (frequencies "abracadabra"))
(prn (partition 2 (interleave [:a :b] [1 2])))
(prn (= (list 1 2) (seq [1 2])))
(prn (keyword "k") (symbol "s"))
(prn (pr-str {:nested [1 #{:a} (list "x")]}))
(println "println-works")
(binding [*print-length* 2] (prn [1 2 3 4]))
(prn (lazy-seq (cons 1 (lazy-seq nil))))
(prn (take 3 (iterate inc 0)))
(prn (group-by odd? (range 6)))
(prn (get-in {:a {:b {:c 1}}} [:a :b :c]))
